CREATE TABLE TB_BOARD (
    BOARD_ID INTEGER AUTO_INCREMENT NOT NULL,
    BOARD_TYPE VARCHAR(20) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(4000) NOT NULL,
    WRITER_ID VARCHAR(50) NOT NULL,
    WRITER_NM VARCHAR(100) NOT NULL,
    VIEW_CNT INTEGER DEFAULT 0 NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_DATETIME NOT NULL,
    MOD_DT DATETIME,
    CONSTRAINT PK_TB_BOARD PRIMARY KEY (BOARD_ID)
);

CREATE INDEX IX_TB_BOARD_TYPE_REG_DT ON TB_BOARD (BOARD_TYPE, REG_DT);
CREATE INDEX IX_TB_BOARD_WRITER ON TB_BOARD (WRITER_ID);