CREATE TABLE TB_LUNCH_VOTE (
    VOTE_ID INTEGER AUTO_INCREMENT NOT NULL,
    VOTE_DT DATE DEFAULT CURRENT_DATE NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    USER_NM VARCHAR(100) NOT NULL,
    RESTAURANT_ID INTEGER NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_DATETIME NOT NULL,
    CONSTRAINT PK_TB_LUNCH_VOTE PRIMARY KEY (VOTE_ID),
    CONSTRAINT UK_TB_LUNCH_VOTE_USER UNIQUE (VOTE_DT, USER_ID)
);

CREATE INDEX IX_TB_LUNCH_VOTE_REST ON TB_LUNCH_VOTE (VOTE_DT, RESTAURANT_ID);
CREATE INDEX IX_TB_LUNCH_VOTE_USER ON TB_LUNCH_VOTE (USER_ID, VOTE_DT);