CREATE TABLE TB_RESTAURANT_COMMENT (
    COMMENT_ID INTEGER AUTO_INCREMENT NOT NULL,
    RESTAURANT_ID INTEGER NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    USER_NM VARCHAR(100) NOT NULL,
    COMMENT_TEXT VARCHAR(1000) NOT NULL,
    DEL_YN CHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_DATETIME NOT NULL,
    MOD_DT DATETIME,
    CONSTRAINT PK_TB_RESTAURANT_COMMENT PRIMARY KEY (COMMENT_ID)
);

CREATE INDEX IX_TB_REST_COMMENT_REST_ID ON TB_RESTAURANT_COMMENT (RESTAURANT_ID, REG_DT);
CREATE INDEX IX_TB_REST_COMMENT_USER_ID ON TB_RESTAURANT_COMMENT (USER_ID);