CREATE TABLE TB_RESTAURANT (
    RESTAURANT_ID INTEGER AUTO_INCREMENT NOT NULL,
    RESTAURANT_NM VARCHAR(200) NOT NULL,
    STORE_NM VARCHAR(200) NOT NULL,
    IMAGE_PATH VARCHAR(500),
    IMAGE_ORG_NM VARCHAR(300),
    MENU_NM VARCHAR(200) NOT NULL,
    CATEGORY_CD VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    LATITUDE NUMERIC(18, 12),
    LONGITUDE NUMERIC(18, 12),
    DESCRIPTION VARCHAR(2000),
    DEL_YN CHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_DATETIME NOT NULL,
    MOD_DT DATETIME,
    CONSTRAINT PK_TB_RESTAURANT PRIMARY KEY (RESTAURANT_ID)
);

CREATE INDEX IX_TB_RESTAURANT_REG_DT ON TB_RESTAURANT (REG_DT);
CREATE INDEX IX_TB_RESTAURANT_CATEGORY ON TB_RESTAURANT (CATEGORY_CD);

-- CATEGORY_CD values: KOREAN, CHINESE, JAPANESE, WESTERN, SNACK, CAFE, ETC
