CREATE TABLE TB_USER (
    USER_ID VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(64) NOT NULL,
    USER_NM VARCHAR(100) NOT NULL,
    PHONE_NO VARCHAR(50),
    REG_DT DATETIME DEFAULT CURRENT_DATETIME NOT NULL,
    CONSTRAINT PK_TB_USER PRIMARY KEY (USER_ID)
);
